[package]
description = "Cartesi Logger Manager"
homepage = "https://cartesi.io"
name = "logger_interface"
version = "0.1.0"
authors = ["Cartesi Team"]

[dependencies]
protobuf = "2"
grpc = "~0.6"
protoc-rust-grpc = "0.6.1"

[[bin]]
name = "build-logger-interface"
path = "src/build.rs"
