name: Documentation
on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      # run protoc-gen-doc
      - name: Generate Documentation
        run: make doc

      # save artifact for publishing
      - name: Save Artifact
        uses: actions/upload-artifact@v1
        with:
          name: doc
          path: doc/
